steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.19.0'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Compile and package'
